In [1]:
import numpy as np

# Creating a numpy Array

In [ ]:
a = ([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a = np.array(a,dtype=float)
a

# numpy zeros method:

In [ ]:
b = np.zeros(2,dtype=int)
print("Matrix b :\n",b)

c = np.zeros([2,2],dtype=int)
print("\nMatrix c :\n",c)

d = np.zeros([3,3])
print("\nMatrix d :\n",d)

# Reshaping the array:

In [ ]:
array1 = np.arange(8)
print("Original array :\n",array1)

array2 = np.arange(8).reshape(2,4)
print("2 rows 4 columns array :\n",array2)

array3 = np.arange(8).reshape(4,2)
print("4 rows 2 columns array :\n",array3)

array4 = np.arange(8).reshape(2,2,2)
print("3D array :\n",array4)

# In the print statement:

In [ ]:
print("A\n",np.arange(4).reshape(2,2),"\n")

print("A\n",np.arange(4,10).reshape(2,3),"\n")

print("A\n",np.arange(4,20,3).reshape(3,2),"\n")

# linspace

In [5]:
# retstep = True shows the difference b/w each elements
# num = 5 is the no of steps
print("B\n", np.linspace(2.0, 3.0, num=5, retstep=True), "\n")

# To evaluate sin() in long range
x = np.linspace(0, 2, 10)
print("A\n", np.sin(x))

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


# Flatten

In [8]:
array5 = np.array([[1, 2], [3, 4]])

array5.flatten()
print(array5)

# F stands for first
# first style google it
array5.flatten('F')
print(array5)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
2


# print largest element

In [12]:
array6 = np.arange(1,10).reshape(3,3)

print("Max :",array6.max())
print("Row-wise max :",array6.max(axis=1))
print("Column-wise max :",array6.max(axis=0))
print("Sum :",array6.sum())
print("Cumulative sum along each row :",array6.cumsum(axis=1))
# axis = 0 means columns
# axis = 1 means rows

Max : 9
Row-wise max : [3 6 9]
Column-wise max : [7 8 9]
Sum : 45
Cumulative sum along each row : [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [13]:
list1 = [1,2,3,4,5,6]
list2 = [10,9,8,7,6,5]

a1 = np.array(list1)
a2 = np.array(list2)

print(a1*a2)

[10 18 24 28 30 30]


In [17]:
array7 = np.arange(10, 1, -2)
print("Negative step array :",array7)

newarr = array7[np.array([3, 1, 2])]
print("Elements at [3, 1, 2] indices are :",newarr)

negative step : [10  8  6  4  2]
Elements at [3, 1, 2] indices are : [4 8 6]


In [21]:
array8 = np.array([[-1,2,0,4],
                   [4,-0.5,6,0],
                   [2.6,0,7,8],
                   [3,-7,4,2.0]])
temp = array8[:2, ::2]
print("temp :\n",temp)

temp = array8[[0, 1, 2, 3], [3, 2, 1, 0]]
print("temp :\n",temp)

cond = array8 > 0
temp = array8[cond]
print("temp :\n",temp)

temp :
 [[-1.  0.]
 [ 4.  6.]]
temp :
 [4. 6. 0. 3.]
temp :
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# negative indexing

In [31]:
array9 = np.arange(1,10)
array9[-3:]

array([7, 8, 9])

# itering over a array

In [25]:
array10 = np.arange(12).reshape(3,4)
print("Original :",array10,"\n")
print("Elements :")
for i in np.nditer(array10):
    print(i)

Original : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Elements :
0
1
2
3
4
5
6
7
8
9
10
11


In [26]:
array11 = np.arange(0,60,5)
array11

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

# mathematical functions

In [33]:
import numpy as np
import math

in_array = [0, math.pi/2, np.pi/3, np.pi]
print("in_array :",in_array)

cos_Values = np.cos(in_array)
print("cos_Values :",cos_Values)

in_array : [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]
cos_Values : [ 1.000000e+00  6.123234e-17  5.000000e-01 -1.000000e+00]


# string operations

In [35]:
print(np.char.lower(['SIDDHANT', 'PAWAR']))

['siddhant' 'pawar']


In [36]:
print(np.char.split('siddhant pawar 13 2001'))

['siddhant', 'pawar', '13', '2001']


In [37]:
print(np.char.join(['-',':'], ['siddhant', 'pawar']))

['s-i-d-d-h-a-n-t' 'p:a:w:a:r']
